name: Build Windows C++ Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Set up SDL2 and extensions
      - name: Set up SDL2
        uses: libsdl-org/setup-sdl@main
        with:
          version: 2-latest
          version-sdl-image: 2-latest
          version-sdl-mixer: 2-latest
          version-sdl-ttf: 2-latest

      # 3. Configure CMake for Visual Studio 2022 x64
      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      # 4. Build with CMake
      - name: Build with CMake
        run: cmake --build build --config Release

      # 5. Copy all SDL2 DLLs to the Release folder
      - name: Copy SDL2 DLLs
        run: |
          copy "%SDL2_ROOT%\lib\x64\SDL2.dll" build\Release\
          copy "%SDL2_IMAGE_ROOT%\lib\x64\SDL2_image.dll" build\Release\
          copy "%SDL2_MIXER_ROOT%\lib\x64\SDL2_mixer.dll" build\Release\
          copy "%SDL2_TTF_ROOT%\lib\x64\SDL2_ttf.dll" build\Release\
        shell: cmd

      # 6. Upload the .exe and DLLs as artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-release
          path: |
            build\Release\*.exe
            build\Release\*.dll
