name: Build Windows C++ Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SDL2 and extensions
        uses: libsdl-org/setup-sdl@main
        with:
          version: 2-latest
          version-sdl-image: 2-latest
          version-sdl-mixer: 2-latest
          version-sdl-ttf: 2-latest

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload .exe and DLLs artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-cpp-exe
          path: |
            build/Release/*.exe
            build/Release/*.dll
