name: Build and Package Windows C++ Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NASM
        run: |
          choco install nasm -y
          nasm -v  # Verify installation

      - name: Set up SDL2 and extensions
        uses: libsdl-org/setup-sdl@main
        with:
          version: 2-latest
          version-sdl-image: 2-latest
          version-sdl-mixer: 2-latest
          version-sdl-ttf: 2-latest

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Copy SDL2 DLLs to build output
        run: |
          xcopy /Y /S "%SDL2_DIR%\\bin\\*.dll" "build\\Release\\"
          xcopy /Y /S "%SDL2_IMAGE_DIR%\\bin\\*.dll" "build\\Release\\"
          xcopy /Y /S "%SDL2_MIXER_DIR%\\bin\\*.dll" "build\\Release\\"
          xcopy /Y /S "%SDL2_TTF_DIR%\\bin\\*.dll" "build\\Release\\"

      - name: Copy README and licenses
        run: |
          copy README.md build\Release\
          copy %SDL2_DIR%\LICENSE.txt build\Release\LICENSE_SDL2.txt
          copy %SDL2_IMAGE_DIR%\LICENSE.txt build\Release\LICENSE_SDL2_image.txt
          copy %SDL2_MIXER_DIR%\LICENSE.txt build\Release\LICENSE_SDL2_mixer.txt
          copy %SDL2_TTF_DIR%\LICENSE.txt build\Release\LICENSE_SDL2_ttf.txt

      - name: Create release zip
        run: |
          powershell Compress-Archive -Path build\Release\* -DestinationPath release.zip

      - name: Upload release zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tower-defence-release
          path: release.zip
