name: Build Windows C++ Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout code (updated to v4)
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Set up SDL2 first (before CMake configuration)
      - name: Set up SDL2
        uses: libsdl-org/setup-sdl@main
        with:
          version: 2-latest
          version-sdl-image: 2-latest
          version-sdl-mixer: 2-latest
          version-sdl-ttf: 2-latest

      # 3. Configure CMake (simplified)
      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      # 4. Build with CMake (instead of MSBuild)
      - name: Build with CMake
        run: cmake --build build --config Release

      # 5. Copy DLLs (alternative method)
      - name: Copy SDL2 DLLs
        run: |
          copy "%SDL2_ROOT%\lib\x64\*.dll" "build\Release\"
        shell: cmd

      # 6. Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-release
          path: |
            build\Release\*.exe
            build\Release\*.dll
