name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v' (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Setup SDL2
        run: |
          # Create directories for SDL2 libraries
          mkdir -p SDL2/lib/x64
          mkdir -p SDL2_image/lib/x64
          mkdir -p SDL2_mixer/lib/x64
          mkdir -p SDL2_ttf/lib/x64
          mkdir -p SDL2/include
          mkdir -p licenses
          
          # Download SDL2 and extract it
          curl -L https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-devel-2.28.5-VC.zip -o SDL2.zip
          7z x SDL2.zip
          xcopy /E /I SDL2-2.28.5\include SDL2\include
          copy SDL2-2.28.5\lib\x64\*.dll SDL2\lib\x64\
          copy SDL2-2.28.5\lib\x64\*.lib SDL2\lib\x64\
          
          # Download SDL2_image and extract it
          curl -L https://github.com/libsdl-org/SDL_image/releases/download/release-2.6.3/SDL2_image-devel-2.6.3-VC.zip -o SDL2_image.zip
          7z x SDL2_image.zip
          copy SDL2_image-2.6.3\lib\x64\*.dll SDL2_image\lib\x64\
          copy SDL2_image-2.6.3\lib\x64\*.lib SDL2_image\lib\x64\
          
          # Download SDL2_mixer and extract it
          curl -L https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.3/SDL2_mixer-devel-2.6.3-VC.zip -o SDL2_mixer.zip
          7z x SDL2_mixer.zip
          copy SDL2_mixer-2.6.3\lib\x64\*.dll SDL2_mixer\lib\x64\
          copy SDL2_mixer-2.6.3\lib\x64\*.lib SDL2_mixer\lib\x64\
          
          # Download SDL2_ttf and extract it
          curl -L https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.2/SDL2_ttf-devel-2.20.2-VC.zip -o SDL2_ttf.zip
          7z x SDL2_ttf.zip
          copy SDL2_ttf-2.20.2\lib\x64\*.dll SDL2_ttf\lib\x64\
          copy SDL2_ttf-2.20.2\lib\x64\*.lib SDL2_ttf\lib\x64\
          
          # Extract SDL2 licenses - with error handling
          if exist SDL2-2.28.5\COPYING.txt (
            copy SDL2-2.28.5\COPYING.txt licenses\SDL2-COPYING.txt
          ) else (
            echo "SDL2 license file not found, creating placeholder"
            echo "See SDL2 license at: https://www.libsdl.org/license.php" > licenses\SDL2-COPYING.txt
          )
          
          if exist SDL2_image-2.6.3\COPYING.txt (
            copy SDL2_image-2.6.3\COPYING.txt licenses\SDL2_image-COPYING.txt
          ) else (
            echo "SDL2_image license file not found, creating placeholder"
            echo "See SDL2_image license at: https://www.libsdl.org/projects/SDL_image/license.php" > licenses\SDL2_image-COPYING.txt
          )
          
          if exist SDL2_mixer-2.6.3\COPYING.txt (
            copy SDL2_mixer-2.6.3\COPYING.txt licenses\SDL2_mixer-COPYING.txt
          ) else (
            echo "SDL2_mixer license file not found, creating placeholder"
            echo "See SDL2_mixer license at: https://www.libsdl.org/projects/SDL_mixer/license.php" > licenses\SDL2_mixer-COPYING.txt
          )
          
          if exist SDL2_ttf-2.20.2\COPYING.txt (
            copy SDL2_ttf-2.20.2\COPYING.txt licenses\SDL2_ttf-COPYING.txt
          ) else (
            echo "SDL2_ttf license file not found, creating placeholder"
            echo "See SDL2_ttf license at: https://www.libsdl.org/projects/SDL_ttf/license.php" > licenses\SDL2_ttf-COPYING.txt
          )
          
          # Debug: List directory contents to help identify issues
          echo "Listing extracted directories:"
          dir SDL2* /b
          
          # Copy all DLLs to a common directory for later inclusion
          mkdir -p SDL_DLLs
          copy SDL2-2.28.5\lib\x64\*.dll SDL_DLLs\
          copy SDL2_image-2.6.3\lib\x64\*.dll SDL_DLLs\
          copy SDL2_mixer-2.6.3\lib\x64\*.dll SDL_DLLs\
          copy SDL2_ttf-2.20.2\lib\x64\*.dll SDL_DLLs\

      - name: Build with MSBuild
        run: msbuild Prog2Engine.sln /p:Configuration=Release

      - name: Create README file
        run: |
          echo "# DAE Tower Defence" > README.md
          echo "" >> README.md
          echo "## Description" >> README.md
          echo "A tower defence game created as part of the DAE programming curriculum." >> README.md
          echo "" >> README.md
          echo "## Controls" >> README.md
          echo "- **Left Mouse Button**: Select and place towers" >> README.md
          echo "- **Right Mouse Button**: Cancel selection" >> README.md
          echo "- **ESC**: Exit game" >> README.md
          echo "" >> README.md
          echo "## System Requirements" >> README.md
          echo "- Windows 10 or later" >> README.md
          echo "- Graphics card supporting DirectX 11" >> README.md
          echo "" >> README.md
          echo "## Installation" >> README.md
          echo "1. Extract all files from the ZIP" >> README.md
          echo "2. Run the DAE-Tower_Defence.exe file" >> README.md
          echo "" >> README.md
          echo "## Credits" >> README.md
          echo "This game uses SDL2 libraries (SDL2, SDL2_image, SDL2_mixer, SDL2_ttf)." >> README.md
          echo "See the licenses folder for license information." >> README.md

      - name: Create combined licenses file
        run: |
          echo "# License Information" > LICENSES.md
          echo "" >> LICENSES.md
          echo "## DAE Tower Defence" >> LICENSES.md
          echo "Copyright (c) 2025 xandermeyen21" >> LICENSES.md
          echo "" >> LICENSES.md
          echo "## Third-Party Libraries" >> LICENSES.md
          echo "" >> LICENSES.md
          echo "This application uses the following third-party libraries:" >> LICENSES.md
          echo "" >> LICENSES.md
          echo "### SDL2" >> LICENSES.md
          echo "See licenses/SDL2-COPYING.txt" >> LICENSES.md
          echo "" >> LICENSES.md
          echo "### SDL2_image" >> LICENSES.md
          echo "See licenses/SDL2_image-COPYING.txt" >> LICENSES.md
          echo "" >> LICENSES.md
          echo "### SDL2_mixer" >> LICENSES.md
          echo "See licenses/SDL2_mixer-COPYING.txt" >> LICENSES.md
          echo "" >> LICENSES.md
          echo "### SDL2_ttf" >> LICENSES.md
          echo "See licenses/SDL2_ttf-COPYING.txt" >> LICENSES.md

      - name: Prepare distribution directory
        run: |
          mkdir -p dist
          copy x64\Release\*.exe dist\
          copy SDL_DLLs\*.dll dist\
          copy README.md dist\
          copy LICENSES.md dist\
          mkdir -p dist\licenses
          copy licenses\*.txt dist\licenses\
          
          # Check if resources directory exists and copy it
          if exist Resources (
            xcopy /E /I Resources dist\Resources
          )
          if exist resources (
            xcopy /E /I resources dist\resources
          )
          if exist Assets (
            xcopy /E /I Assets dist\Assets
          )
          if exist assets (
            xcopy /E /I assets dist\assets
          )

      - name: List distribution directory
        run: |
          dir dist /s

      - name: Create ZIP archive
        run: |
          powershell Compress-Archive -Path dist\* -DestinationPath DAE-Tower_Defence.zip
          
      - name: Extract tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: DAE-Tower_Defence.zip
          draft: false
          prerelease: false
          name: "DAE Tower Defence ${{ steps.get_version.outputs.VERSION }}"
          body: |
            # DAE Tower Defence ${{ steps.get_version.outputs.VERSION }}
            
            ## What's New
            - New release with complete package including resources and documentation
            
            ## Installation
            1. Download the ZIP file
            2. Extract all files
            3. Run DAE-Tower_Defence.exe
